### ISSUE TITLE
Les titres longs de randonnées sont tronqués en vue mobile

### ISSUE THREAD

**Issue by bruhnild** [GeotrekCE/Geotrek-rando-v3#1160]
Sur la vignette (vue liste) d'une randonnée, lorsque le titre tient sur deux lignes, celui-ci est tronqué sur la vue mobile.

Exemple  : https://rando.vanoise.com/search?text=Tour%20de%20la%20pointe%20de%20la%20Vallaisonnay

![image](https://github.com/GeotrekCE/Geotrek-rando-v3/assets/26433045/f6613f58-43d9-4532-8ba3-7f033741228a)

Une custo CSS peut être ajoutée dans le fichier customization/theme/style.css mais il serait plus pérenne de l'intégrer directement au produit : 

```css
.custo-result-card h2,
.custo-result-card h3 {
  text-overflow: inherit;
  white-space: unset;
}
```

NB: la class `custo-result-card` n'apparait qu'à partir de la 3.19.0.
